package com.easy.work.org.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.org.dto.OrgMenuDto;

import java.util.Date;

@Table(name = "SYS_ORG_MENU")
public class OrgMenuDomain extends OrgMenuDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ORG_MENU.ORG_MENU_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    @Column(id = "ORG_MENU_ID",increment = true,length = 12,rule = "OM")
    private String orgMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ORG_MENU.ORG_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ORG_MENU.MENU_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ORG_MENU.CREATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ORG_MENU.CREATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ORG_MENU.UPDATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ORG_MENU.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ORG_MENU.ORG_MENU_ID
     *
     * @return the value of SYS_ORG_MENU.ORG_MENU_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public String getOrgMenuId() {
        return orgMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ORG_MENU.ORG_MENU_ID
     *
     * @param orgMenuId the value for SYS_ORG_MENU.ORG_MENU_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setOrgMenuId(String orgMenuId) {
        this.orgMenuId = orgMenuId == null ? null : orgMenuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ORG_MENU.ORG_ID
     *
     * @return the value of SYS_ORG_MENU.ORG_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ORG_MENU.ORG_ID
     *
     * @param orgId the value for SYS_ORG_MENU.ORG_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ORG_MENU.MENU_ID
     *
     * @return the value of SYS_ORG_MENU.MENU_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ORG_MENU.MENU_ID
     *
     * @param menuId the value for SYS_ORG_MENU.MENU_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ORG_MENU.CREATER
     *
     * @return the value of SYS_ORG_MENU.CREATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ORG_MENU.CREATER
     *
     * @param creater the value for SYS_ORG_MENU.CREATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ORG_MENU.CREATE_TIME
     *
     * @return the value of SYS_ORG_MENU.CREATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ORG_MENU.CREATE_TIME
     *
     * @param createTime the value for SYS_ORG_MENU.CREATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ORG_MENU.UPDATER
     *
     * @return the value of SYS_ORG_MENU.UPDATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ORG_MENU.UPDATER
     *
     * @param updater the value for SYS_ORG_MENU.UPDATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ORG_MENU.UPDATE_TIME
     *
     * @return the value of SYS_ORG_MENU.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ORG_MENU.UPDATE_TIME
     *
     * @param updateTime the value for SYS_ORG_MENU.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}