package com.easy.work.city.domain;

import com.easy.work.city.dto.CityDto;

import java.util.Date;

public class CityDomain extends CityDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.version
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.code
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.create_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.has_mall
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Boolean hasMall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.name
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.op_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private String opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.province_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Long provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.update_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.id
     *
     * @return the value of city.id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.id
     *
     * @param id the value for city.id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.version
     *
     * @return the value of city.version
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.version
     *
     * @param version the value for city.version
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.code
     *
     * @return the value of city.code
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.code
     *
     * @param code the value for city.code
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.create_time
     *
     * @return the value of city.create_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.create_time
     *
     * @param createTime the value for city.create_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.has_mall
     *
     * @return the value of city.has_mall
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Boolean getHasMall() {
        return hasMall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.has_mall
     *
     * @param hasMall the value for city.has_mall
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setHasMall(Boolean hasMall) {
        this.hasMall = hasMall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.name
     *
     * @return the value of city.name
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.name
     *
     * @param name the value for city.name
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.op_id
     *
     * @return the value of city.op_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public String getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.op_id
     *
     * @param opId the value for city.op_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setOpId(String opId) {
        this.opId = opId == null ? null : opId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.province_id
     *
     * @return the value of city.province_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.province_id
     *
     * @param provinceId the value for city.province_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.update_time
     *
     * @return the value of city.update_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.update_time
     *
     * @param updateTime the value for city.update_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}