package com.easy.work.dictionary.domain;

import com.easy.work.dictionary.dto.DictionaryDto;

import java.util.Date;

public class DictionaryDomain extends DictionaryDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICTIONARY.DICTIONARY_ID
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    private String dictionaryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICTIONARY.DICTIONARY_CODE
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    private String dictionaryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICTIONARY.DICTIONARY_NAME
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    private String dictionaryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICTIONARY.DICTIONARY_TYPE
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    private String dictionaryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICTIONARY.CREATER
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICTIONARY.CREATE_TIME
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICTIONARY.UPDATER
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DICTIONARY.UPDATE_TIME
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICTIONARY.DICTIONARY_ID
     *
     * @return the value of SYS_DICTIONARY.DICTIONARY_ID
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public String getDictionaryId() {
        return dictionaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICTIONARY.DICTIONARY_ID
     *
     * @param dictionaryId the value for SYS_DICTIONARY.DICTIONARY_ID
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public void setDictionaryId(String dictionaryId) {
        this.dictionaryId = dictionaryId == null ? null : dictionaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICTIONARY.DICTIONARY_CODE
     *
     * @return the value of SYS_DICTIONARY.DICTIONARY_CODE
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public String getDictionaryCode() {
        return dictionaryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICTIONARY.DICTIONARY_CODE
     *
     * @param dictionaryCode the value for SYS_DICTIONARY.DICTIONARY_CODE
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public void setDictionaryCode(String dictionaryCode) {
        this.dictionaryCode = dictionaryCode == null ? null : dictionaryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICTIONARY.DICTIONARY_NAME
     *
     * @return the value of SYS_DICTIONARY.DICTIONARY_NAME
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public String getDictionaryName() {
        return dictionaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICTIONARY.DICTIONARY_NAME
     *
     * @param dictionaryName the value for SYS_DICTIONARY.DICTIONARY_NAME
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public void setDictionaryName(String dictionaryName) {
        this.dictionaryName = dictionaryName == null ? null : dictionaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICTIONARY.DICTIONARY_TYPE
     *
     * @return the value of SYS_DICTIONARY.DICTIONARY_TYPE
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public String getDictionaryType() {
        return dictionaryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICTIONARY.DICTIONARY_TYPE
     *
     * @param dictionaryType the value for SYS_DICTIONARY.DICTIONARY_TYPE
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public void setDictionaryType(String dictionaryType) {
        this.dictionaryType = dictionaryType == null ? null : dictionaryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICTIONARY.CREATER
     *
     * @return the value of SYS_DICTIONARY.CREATER
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICTIONARY.CREATER
     *
     * @param creater the value for SYS_DICTIONARY.CREATER
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICTIONARY.CREATE_TIME
     *
     * @return the value of SYS_DICTIONARY.CREATE_TIME
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICTIONARY.CREATE_TIME
     *
     * @param createTime the value for SYS_DICTIONARY.CREATE_TIME
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICTIONARY.UPDATER
     *
     * @return the value of SYS_DICTIONARY.UPDATER
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICTIONARY.UPDATER
     *
     * @param updater the value for SYS_DICTIONARY.UPDATER
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DICTIONARY.UPDATE_TIME
     *
     * @return the value of SYS_DICTIONARY.UPDATE_TIME
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DICTIONARY.UPDATE_TIME
     *
     * @param updateTime the value for SYS_DICTIONARY.UPDATE_TIME
     *
     * @mbg.generated Wed Jun 27 08:16:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}