package com.easy.work.forms.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.forms.dto.FormsDto;

import java.util.Date;

@Table(name="SYS_FORMS")
public class FormsDomain extends FormsDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.FORM_ID
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    @Column(id="FORM_ID",increment = true,length = 12,rule = "FR")
    private String formId;


    private String objId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.FORM_TITLE
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    private String formTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.FORM_ACTION
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    private String formAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.FORM_TYPE
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    private String formType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.PROCESS_ID
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    private String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.FORM_REMARK
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    private String formRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.CREATE_TIME
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.CREATER
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.UPDATER
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_FORMS.FORM_HTML
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    private String formHtml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.FORM_ID
     *
     * @return the value of SYS_FORMS.FORM_ID
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.FORM_ID
     *
     * @param formId the value for SYS_FORMS.FORM_ID
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setFormId(String formId) {
        this.formId = formId == null ? null : formId.trim();
    }

    public String getObjId() {
        return objId;
    }

    public void setObjId(String objId) {
        this.objId = objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.FORM_TITLE
     *
     * @return the value of SYS_FORMS.FORM_TITLE
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public String getFormTitle() {
        return formTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.FORM_TITLE
     *
     * @param formTitle the value for SYS_FORMS.FORM_TITLE
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setFormTitle(String formTitle) {
        this.formTitle = formTitle == null ? null : formTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.FORM_ACTION
     *
     * @return the value of SYS_FORMS.FORM_ACTION
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public String getFormAction() {
        return formAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.FORM_ACTION
     *
     * @param formAction the value for SYS_FORMS.FORM_ACTION
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setFormAction(String formAction) {
        this.formAction = formAction == null ? null : formAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.FORM_TYPE
     *
     * @return the value of SYS_FORMS.FORM_TYPE
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public String getFormType() {
        return formType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.FORM_TYPE
     *
     * @param formType the value for SYS_FORMS.FORM_TYPE
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setFormType(String formType) {
        this.formType = formType == null ? null : formType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.PROCESS_ID
     *
     * @return the value of SYS_FORMS.PROCESS_ID
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.PROCESS_ID
     *
     * @param processId the value for SYS_FORMS.PROCESS_ID
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.FORM_REMARK
     *
     * @return the value of SYS_FORMS.FORM_REMARK
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public String getFormRemark() {
        return formRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.FORM_REMARK
     *
     * @param formRemark the value for SYS_FORMS.FORM_REMARK
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setFormRemark(String formRemark) {
        this.formRemark = formRemark == null ? null : formRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.CREATE_TIME
     *
     * @return the value of SYS_FORMS.CREATE_TIME
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.CREATE_TIME
     *
     * @param createTime the value for SYS_FORMS.CREATE_TIME
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.CREATER
     *
     * @return the value of SYS_FORMS.CREATER
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.CREATER
     *
     * @param creater the value for SYS_FORMS.CREATER
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.UPDATE_TIME
     *
     * @return the value of SYS_FORMS.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.UPDATE_TIME
     *
     * @param updateTime the value for SYS_FORMS.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.UPDATER
     *
     * @return the value of SYS_FORMS.UPDATER
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.UPDATER
     *
     * @param updater the value for SYS_FORMS.UPDATER
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_FORMS.FORM_HTML
     *
     * @return the value of SYS_FORMS.FORM_HTML
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public String getFormHtml() {
        return formHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_FORMS.FORM_HTML
     *
     * @param formHtml the value for SYS_FORMS.FORM_HTML
     *
     * @mbg.generated Mon Apr 16 11:27:46 CST 2018
     */
    public void setFormHtml(String formHtml) {
        this.formHtml = formHtml == null ? null : formHtml.trim();
    }
}