package com.easy.work.role.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.role.dto.RoleDto;

import java.util.Date;

@Table(name="sys_role")
public class RoleDomain extends RoleDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_ID
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    @Column(id = "ROLE_ID", rule = "RL", increment = true, length = 12)
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_CODE
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_NAME
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_TYPE
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_STATUS
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    private String roleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_RANGE
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    private String roleRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLE_REMARK
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    private String roleRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.CREATE_TIME
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.CREATER
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.UPDATER
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_ID
     *
     * @return the value of SYS_ROLE.ROLE_ID
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_ID
     *
     * @param roleId the value for SYS_ROLE.ROLE_ID
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_CODE
     *
     * @return the value of SYS_ROLE.ROLE_CODE
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_CODE
     *
     * @param roleCode the value for SYS_ROLE.ROLE_CODE
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_NAME
     *
     * @return the value of SYS_ROLE.ROLE_NAME
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_NAME
     *
     * @param roleName the value for SYS_ROLE.ROLE_NAME
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_TYPE
     *
     * @return the value of SYS_ROLE.ROLE_TYPE
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_TYPE
     *
     * @param roleType the value for SYS_ROLE.ROLE_TYPE
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_STATUS
     *
     * @return the value of SYS_ROLE.ROLE_STATUS
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public String getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_STATUS
     *
     * @param roleStatus the value for SYS_ROLE.ROLE_STATUS
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setRoleStatus(String roleStatus) {
        this.roleStatus = roleStatus == null ? null : roleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_RANGE
     *
     * @return the value of SYS_ROLE.ROLE_RANGE
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public String getRoleRange() {
        return roleRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_RANGE
     *
     * @param roleRange the value for SYS_ROLE.ROLE_RANGE
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setRoleRange(String roleRange) {
        this.roleRange = roleRange == null ? null : roleRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLE_REMARK
     *
     * @return the value of SYS_ROLE.ROLE_REMARK
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public String getRoleRemark() {
        return roleRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLE_REMARK
     *
     * @param roleRemark the value for SYS_ROLE.ROLE_REMARK
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setRoleRemark(String roleRemark) {
        this.roleRemark = roleRemark == null ? null : roleRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.CREATE_TIME
     *
     * @return the value of SYS_ROLE.CREATE_TIME
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.CREATE_TIME
     *
     * @param createTime the value for SYS_ROLE.CREATE_TIME
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.CREATER
     *
     * @return the value of SYS_ROLE.CREATER
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.CREATER
     *
     * @param creater the value for SYS_ROLE.CREATER
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.UPDATE_TIME
     *
     * @return the value of SYS_ROLE.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.UPDATE_TIME
     *
     * @param updateTime the value for SYS_ROLE.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.UPDATER
     *
     * @return the value of SYS_ROLE.UPDATER
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.UPDATER
     *
     * @param updater the value for SYS_ROLE.UPDATER
     *
     * @mbg.generated Thu Jun 21 13:38:43 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}