package com.easy.work.role.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.role.dto.RoleMenuDto;

import java.util.Date;

@Table(name = "SYS_ROLE_MENU")
public class RoleMenuDomain extends RoleMenuDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_MENU.ROLE_MENU_ID
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    @Column(id = "ROLE_MENU_ID",increment = true,length = 12,rule = "RM")
    private String roleMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_MENU.ROLE_ID
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_MENU.MENU_ID
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_MENU.CREATER
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_MENU.CREATE_TIME
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_MENU.UPDATER
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_MENU.UPDATE_TIME
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_MENU.ROLE_MENU_ID
     *
     * @return the value of SYS_ROLE_MENU.ROLE_MENU_ID
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public String getRoleMenuId() {
        return roleMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_MENU.ROLE_MENU_ID
     *
     * @param roleMenuId the value for SYS_ROLE_MENU.ROLE_MENU_ID
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public void setRoleMenuId(String roleMenuId) {
        this.roleMenuId = roleMenuId == null ? null : roleMenuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_MENU.ROLE_ID
     *
     * @return the value of SYS_ROLE_MENU.ROLE_ID
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_MENU.ROLE_ID
     *
     * @param roleId the value for SYS_ROLE_MENU.ROLE_ID
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_MENU.MENU_ID
     *
     * @return the value of SYS_ROLE_MENU.MENU_ID
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_MENU.MENU_ID
     *
     * @param menuId the value for SYS_ROLE_MENU.MENU_ID
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_MENU.CREATER
     *
     * @return the value of SYS_ROLE_MENU.CREATER
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_MENU.CREATER
     *
     * @param creater the value for SYS_ROLE_MENU.CREATER
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_MENU.CREATE_TIME
     *
     * @return the value of SYS_ROLE_MENU.CREATE_TIME
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_MENU.CREATE_TIME
     *
     * @param createTime the value for SYS_ROLE_MENU.CREATE_TIME
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_MENU.UPDATER
     *
     * @return the value of SYS_ROLE_MENU.UPDATER
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_MENU.UPDATER
     *
     * @param updater the value for SYS_ROLE_MENU.UPDATER
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_MENU.UPDATE_TIME
     *
     * @return the value of SYS_ROLE_MENU.UPDATE_TIME
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_MENU.UPDATE_TIME
     *
     * @param updateTime the value for SYS_ROLE_MENU.UPDATE_TIME
     *
     * @mbg.generated Mon Jul 02 10:49:27 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}