package com.easy.work.role.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.role.dto.RoleOrgDto;

import java.util.Date;

@Table(name = "SYS_ROLE_ORG")
public class RoleOrgDomain extends RoleOrgDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ORG.ROLE_ORG_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    @Column(id = "ROLE_ORG_ID",increment = true,length = 12,rule = "RO")
    private String roleOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ORG.ROLE_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ORG.ORG_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ORG.CREATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ORG.CREATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ORG.UPDATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ORG.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ORG.ROLE_ORG_ID
     *
     * @return the value of SYS_ROLE_ORG.ROLE_ORG_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public String getRoleOrgId() {
        return roleOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ORG.ROLE_ORG_ID
     *
     * @param roleOrgId the value for SYS_ROLE_ORG.ROLE_ORG_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setRoleOrgId(String roleOrgId) {
        this.roleOrgId = roleOrgId == null ? null : roleOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ORG.ROLE_ID
     *
     * @return the value of SYS_ROLE_ORG.ROLE_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ORG.ROLE_ID
     *
     * @param roleId the value for SYS_ROLE_ORG.ROLE_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ORG.ORG_ID
     *
     * @return the value of SYS_ROLE_ORG.ORG_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ORG.ORG_ID
     *
     * @param orgId the value for SYS_ROLE_ORG.ORG_ID
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ORG.CREATER
     *
     * @return the value of SYS_ROLE_ORG.CREATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ORG.CREATER
     *
     * @param creater the value for SYS_ROLE_ORG.CREATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ORG.CREATE_TIME
     *
     * @return the value of SYS_ROLE_ORG.CREATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ORG.CREATE_TIME
     *
     * @param createTime the value for SYS_ROLE_ORG.CREATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ORG.UPDATER
     *
     * @return the value of SYS_ROLE_ORG.UPDATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ORG.UPDATER
     *
     * @param updater the value for SYS_ROLE_ORG.UPDATER
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ORG.UPDATE_TIME
     *
     * @return the value of SYS_ROLE_ORG.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ORG.UPDATE_TIME
     *
     * @param updateTime the value for SYS_ROLE_ORG.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 28 08:34:38 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}