package com.easy.work.district.domain;

import com.easy.work.district.dto.DistrictDto;

import java.util.Date;

public class DistrictDomain extends DistrictDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.version
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.city_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Long cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.code
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.create_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.name
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.op_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private String opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.update_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.id
     *
     * @return the value of district.id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.id
     *
     * @param id the value for district.id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.version
     *
     * @return the value of district.version
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.version
     *
     * @param version the value for district.version
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.city_id
     *
     * @return the value of district.city_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.city_id
     *
     * @param cityId the value for district.city_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.code
     *
     * @return the value of district.code
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.code
     *
     * @param code the value for district.code
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.create_time
     *
     * @return the value of district.create_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.create_time
     *
     * @param createTime the value for district.create_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.name
     *
     * @return the value of district.name
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.name
     *
     * @param name the value for district.name
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.op_id
     *
     * @return the value of district.op_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public String getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.op_id
     *
     * @param opId the value for district.op_id
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setOpId(String opId) {
        this.opId = opId == null ? null : opId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.update_time
     *
     * @return the value of district.update_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.update_time
     *
     * @param updateTime the value for district.update_time
     *
     * @mbg.generated Fri Jun 15 09:13:25 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}