package com.easy.work.tab.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.tab.dto.TabDto;

import java.util.Date;

@Table(name = "sys_tab")
public class TabDomain extends TabDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.TAB_ID
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    @Column(id = "tab_id",increment = true,rule = "TB", length = 12)
    private String tabId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.ORG_ID
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.TAB_NAME
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private String tabName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.TAB_SOURCE_NAME
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private String tabSourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.TAB_TYPE
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private String tabType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.TAB_INDEX
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private String tabIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.TAB_KEY
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private String tabKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.TAB_COMMENT
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private String tabComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.TAB_OPTIONS
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private String tabOptions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.CREATER
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.UPDATER
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.TAB_ID
     *
     * @return the value of SYS_TAB.TAB_ID
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public String getTabId() {
        return tabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.TAB_ID
     *
     * @param tabId the value for SYS_TAB.TAB_ID
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setTabId(String tabId) {
        this.tabId = tabId == null ? null : tabId.trim();
    }

    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.TAB_NAME
     *
     * @return the value of SYS_TAB.TAB_NAME
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public String getTabName() {
        return tabName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.TAB_NAME
     *
     * @param tabName the value for SYS_TAB.TAB_NAME
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setTabName(String tabName) {
        this.tabName = tabName == null ? null : tabName.trim();
    }

    public String getTabSourceName() {
        return tabSourceName;
    }

    public void setTabSourceName(String tabSourceName) {
        this.tabSourceName = tabSourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.TAB_TYPE
     *
     * @return the value of SYS_TAB.TAB_TYPE
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public String getTabType() {
        return tabType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.TAB_TYPE
     *
     * @param tabType the value for SYS_TAB.TAB_TYPE
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setTabType(String tabType) {
        this.tabType = tabType == null ? null : tabType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.TAB_INDEX
     *
     * @return the value of SYS_TAB.TAB_INDEX
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public String getTabIndex() {
        return tabIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.TAB_INDEX
     *
     * @param tabIndex the value for SYS_TAB.TAB_INDEX
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setTabIndex(String tabIndex) {
        this.tabIndex = tabIndex == null ? null : tabIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.TAB_KEY
     *
     * @return the value of SYS_TAB.TAB_KEY
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public String getTabKey() {
        return tabKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.TAB_KEY
     *
     * @param tabKey the value for SYS_TAB.TAB_KEY
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setTabKey(String tabKey) {
        this.tabKey = tabKey == null ? null : tabKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.TAB_COMMENT
     *
     * @return the value of SYS_TAB.TAB_COMMENT
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public String getTabComment() {
        return tabComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.TAB_COMMENT
     *
     * @param tabComment the value for SYS_TAB.TAB_COMMENT
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setTabComment(String tabComment) {
        this.tabComment = tabComment == null ? null : tabComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.TAB_OPTIONS
     *
     * @return the value of SYS_TAB.TAB_OPTIONS
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public String getTabOptions() {
        return tabOptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.TAB_OPTIONS
     *
     * @param tabOptions the value for SYS_TAB.TAB_OPTIONS
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setTabOptions(String tabOptions) {
        this.tabOptions = tabOptions == null ? null : tabOptions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.CREATER
     *
     * @return the value of SYS_TAB.CREATER
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.CREATER
     *
     * @param creater the value for SYS_TAB.CREATER
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.CREATE_TIME
     *
     * @return the value of SYS_TAB.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.CREATE_TIME
     *
     * @param createTime the value for SYS_TAB.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.UPDATER
     *
     * @return the value of SYS_TAB.UPDATER
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.UPDATER
     *
     * @param updater the value for SYS_TAB.UPDATER
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB.UPDATE_TIME
     *
     * @return the value of SYS_TAB.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB.UPDATE_TIME
     *
     * @param updateTime the value for SYS_TAB.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:49:59 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}