package com.easy.work.tab.domain;

import com.easy.work.tab.dto.TabFieldTypeDto;

import java.util.Date;

public class TabFieldTypeDomain extends TabFieldTypeDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD_TYPE.TAB_FIELD_TYPE_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabFieldTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD_TYPE.TAB_FIELD_NAME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabFieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD_TYPE.CREATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD_TYPE.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD_TYPE.UPDATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD_TYPE.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD_TYPE.TAB_FIELD_TYPE_ID
     *
     * @return the value of SYS_TAB_FIELD_TYPE.TAB_FIELD_TYPE_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabFieldTypeId() {
        return tabFieldTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD_TYPE.TAB_FIELD_TYPE_ID
     *
     * @param tabFieldTypeId the value for SYS_TAB_FIELD_TYPE.TAB_FIELD_TYPE_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabFieldTypeId(String tabFieldTypeId) {
        this.tabFieldTypeId = tabFieldTypeId == null ? null : tabFieldTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD_TYPE.TAB_FIELD_NAME
     *
     * @return the value of SYS_TAB_FIELD_TYPE.TAB_FIELD_NAME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabFieldName() {
        return tabFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD_TYPE.TAB_FIELD_NAME
     *
     * @param tabFieldName the value for SYS_TAB_FIELD_TYPE.TAB_FIELD_NAME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabFieldName(String tabFieldName) {
        this.tabFieldName = tabFieldName == null ? null : tabFieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD_TYPE.CREATER
     *
     * @return the value of SYS_TAB_FIELD_TYPE.CREATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD_TYPE.CREATER
     *
     * @param creater the value for SYS_TAB_FIELD_TYPE.CREATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD_TYPE.CREATE_TIME
     *
     * @return the value of SYS_TAB_FIELD_TYPE.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD_TYPE.CREATE_TIME
     *
     * @param createTime the value for SYS_TAB_FIELD_TYPE.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD_TYPE.UPDATER
     *
     * @return the value of SYS_TAB_FIELD_TYPE.UPDATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD_TYPE.UPDATER
     *
     * @param updater the value for SYS_TAB_FIELD_TYPE.UPDATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD_TYPE.UPDATE_TIME
     *
     * @return the value of SYS_TAB_FIELD_TYPE.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD_TYPE.UPDATE_TIME
     *
     * @param updateTime the value for SYS_TAB_FIELD_TYPE.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}