package com.easy.work.tab.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.tab.dto.TabFieldDto;

import java.util.Date;

@Table(name = "sys_tab_field")
public class TabFieldDomain extends TabFieldDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.TAB_FIELD_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    @Column(id = "tab_field_id",length = 12, rule = "TF", increment = true)
    private String tabFieldId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.TAB_IS_KEY
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabIsKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.TAB_IS_NULL
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabIsNull;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.TAB_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.TAB_FIELD_NAME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabFieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.TAB_FIELD_TYPE
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabFieldType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.TAB_FIELD_LENGTH
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabFieldLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.TAB_FIELD_COMMENT
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabFieldComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.CREATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.UPDATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_FIELD.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.TAB_FIELD_ID
     *
     * @return the value of SYS_TAB_FIELD.TAB_FIELD_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabFieldId() {
        return tabFieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.TAB_FIELD_ID
     *
     * @param tabFieldId the value for SYS_TAB_FIELD.TAB_FIELD_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabFieldId(String tabFieldId) {
        this.tabFieldId = tabFieldId == null ? null : tabFieldId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.TAB_IS_KEY
     *
     * @return the value of SYS_TAB_FIELD.TAB_IS_KEY
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabIsKey() {
        return tabIsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.TAB_IS_KEY
     *
     * @param tabIsKey the value for SYS_TAB_FIELD.TAB_IS_KEY
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabIsKey(String tabIsKey) {
        this.tabIsKey = tabIsKey == null ? null : tabIsKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.TAB_IS_NULL
     *
     * @return the value of SYS_TAB_FIELD.TAB_IS_NULL
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabIsNull() {
        return tabIsNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.TAB_IS_NULL
     *
     * @param tabIsNull the value for SYS_TAB_FIELD.TAB_IS_NULL
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabIsNull(String tabIsNull) {
        this.tabIsNull = tabIsNull == null ? null : tabIsNull.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.TAB_ID
     *
     * @return the value of SYS_TAB_FIELD.TAB_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabId() {
        return tabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.TAB_ID
     *
     * @param tabId the value for SYS_TAB_FIELD.TAB_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabId(String tabId) {
        this.tabId = tabId == null ? null : tabId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.TAB_FIELD_NAME
     *
     * @return the value of SYS_TAB_FIELD.TAB_FIELD_NAME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabFieldName() {
        return tabFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.TAB_FIELD_NAME
     *
     * @param tabFieldName the value for SYS_TAB_FIELD.TAB_FIELD_NAME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabFieldName(String tabFieldName) {
        this.tabFieldName = tabFieldName == null ? null : tabFieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.TAB_FIELD_TYPE
     *
     * @return the value of SYS_TAB_FIELD.TAB_FIELD_TYPE
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabFieldType() {
        return tabFieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.TAB_FIELD_TYPE
     *
     * @param tabFieldType the value for SYS_TAB_FIELD.TAB_FIELD_TYPE
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabFieldType(String tabFieldType) {
        this.tabFieldType = tabFieldType == null ? null : tabFieldType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.TAB_FIELD_LENGTH
     *
     * @return the value of SYS_TAB_FIELD.TAB_FIELD_LENGTH
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabFieldLength() {
        return tabFieldLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.TAB_FIELD_LENGTH
     *
     * @param tabFieldLength the value for SYS_TAB_FIELD.TAB_FIELD_LENGTH
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabFieldLength(String tabFieldLength) {
        this.tabFieldLength = tabFieldLength == null ? null : tabFieldLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.TAB_FIELD_COMMENT
     *
     * @return the value of SYS_TAB_FIELD.TAB_FIELD_COMMENT
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabFieldComment() {
        return tabFieldComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.TAB_FIELD_COMMENT
     *
     * @param tabFieldComment the value for SYS_TAB_FIELD.TAB_FIELD_COMMENT
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabFieldComment(String tabFieldComment) {
        this.tabFieldComment = tabFieldComment == null ? null : tabFieldComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.CREATER
     *
     * @return the value of SYS_TAB_FIELD.CREATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.CREATER
     *
     * @param creater the value for SYS_TAB_FIELD.CREATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.CREATE_TIME
     *
     * @return the value of SYS_TAB_FIELD.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.CREATE_TIME
     *
     * @param createTime the value for SYS_TAB_FIELD.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.UPDATER
     *
     * @return the value of SYS_TAB_FIELD.UPDATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.UPDATER
     *
     * @param updater the value for SYS_TAB_FIELD.UPDATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_FIELD.UPDATE_TIME
     *
     * @return the value of SYS_TAB_FIELD.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_FIELD.UPDATE_TIME
     *
     * @param updateTime the value for SYS_TAB_FIELD.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}