package com.easy.work.tab.domain;

import com.easy.work.tab.dto.TabTypeDto;

import java.util.Date;

public class TabTypeDomain extends TabTypeDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_TYPE.TAB_TYPE_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabTypeId;

    private String tabTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_TYPE.TAB_TYPE_NAME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String tabTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_TYPE.CREATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_TYPE.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_TYPE.UPDATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_TAB_TYPE.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_TYPE.TAB_TYPE_ID
     *
     * @return the value of SYS_TAB_TYPE.TAB_TYPE_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabTypeId() {
        return tabTypeId;
    }

    public String getTabTypeCode() {
        return tabTypeCode;
    }

    public void setTabTypeCode(String tabTypeCode) {
        this.tabTypeCode = tabTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_TYPE.TAB_TYPE_ID
     *
     * @param tabTypeId the value for SYS_TAB_TYPE.TAB_TYPE_ID
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabTypeId(String tabTypeId) {
        this.tabTypeId = tabTypeId == null ? null : tabTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_TYPE.TAB_TYPE_NAME
     *
     * @return the value of SYS_TAB_TYPE.TAB_TYPE_NAME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getTabTypeName() {
        return tabTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_TYPE.TAB_TYPE_NAME
     *
     * @param tabTypeName the value for SYS_TAB_TYPE.TAB_TYPE_NAME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setTabTypeName(String tabTypeName) {
        this.tabTypeName = tabTypeName == null ? null : tabTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_TYPE.CREATER
     *
     * @return the value of SYS_TAB_TYPE.CREATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_TYPE.CREATER
     *
     * @param creater the value for SYS_TAB_TYPE.CREATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_TYPE.CREATE_TIME
     *
     * @return the value of SYS_TAB_TYPE.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_TYPE.CREATE_TIME
     *
     * @param createTime the value for SYS_TAB_TYPE.CREATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_TYPE.UPDATER
     *
     * @return the value of SYS_TAB_TYPE.UPDATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_TYPE.UPDATER
     *
     * @param updater the value for SYS_TAB_TYPE.UPDATER
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_TAB_TYPE.UPDATE_TIME
     *
     * @return the value of SYS_TAB_TYPE.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_TAB_TYPE.UPDATE_TIME
     *
     * @param updateTime the value for SYS_TAB_TYPE.UPDATE_TIME
     *
     * @mbg.generated Thu May 17 13:48:08 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}