package com.easy.work.sign.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.sign.dto.SignDto;

import java.util.Date;

@Table(name="sign")
public class SignDomain extends SignDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.SING_ID
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    @Column(id="sing_id",rule = "SG",length = 12,increment = true)
    private String singId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.USER_ID
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.SING_BRANCH
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    private String singBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.CREATE_TIME
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.CREATER
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.UPDATE_TIME
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.UPDATER
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.SING_ID
     *
     * @return the value of sign.SING_ID
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public String getSingId() {
        return singId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.SING_ID
     *
     * @param singId the value for sign.SING_ID
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public void setSingId(String singId) {
        this.singId = singId == null ? null : singId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.USER_ID
     *
     * @return the value of sign.USER_ID
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.USER_ID
     *
     * @param userId the value for sign.USER_ID
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.SING_BRANCH
     *
     * @return the value of sign.SING_BRANCH
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public String getSingBranch() {
        return singBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.SING_BRANCH
     *
     * @param singBranch the value for sign.SING_BRANCH
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public void setSingBranch(String singBranch) {
        this.singBranch = singBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.CREATE_TIME
     *
     * @return the value of sign.CREATE_TIME
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.CREATE_TIME
     *
     * @param createTime the value for sign.CREATE_TIME
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.CREATER
     *
     * @return the value of sign.CREATER
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.CREATER
     *
     * @param creater the value for sign.CREATER
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.UPDATE_TIME
     *
     * @return the value of sign.UPDATE_TIME
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.UPDATE_TIME
     *
     * @param updateTime the value for sign.UPDATE_TIME
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.UPDATER
     *
     * @return the value of sign.UPDATER
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.UPDATER
     *
     * @param updater the value for sign.UPDATER
     *
     * @mbg.generated Wed May 02 12:04:37 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}