package com.easy.work.user.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.user.dto.UserOrgDto;

import java.util.Date;

@Table(name = "SYS_USER_ORG")
public class UserOrgDomain extends UserOrgDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ORG.USER_ORG_ID
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    @Column(id = "user_org_id",rule = "UG",length = 12,increment = true)
    private String userOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ORG.ORG_ID
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ORG.ACCOUNT_ID
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ORG.CREATE_TIME
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ORG.CREATER
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ORG.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ORG.UPDATER
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ORG.USER_ORG_ID
     *
     * @return the value of SYS_USER_ORG.USER_ORG_ID
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public String getUserOrgId() {
        return userOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ORG.USER_ORG_ID
     *
     * @param userOrgId the value for SYS_USER_ORG.USER_ORG_ID
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public void setUserOrgId(String userOrgId) {
        this.userOrgId = userOrgId == null ? null : userOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ORG.ORG_ID
     *
     * @return the value of SYS_USER_ORG.ORG_ID
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ORG.ORG_ID
     *
     * @param orgId the value for SYS_USER_ORG.ORG_ID
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ORG.ACCOUNT_ID
     *
     * @return the value of SYS_USER_ORG.ACCOUNT_ID
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ORG.ACCOUNT_ID
     *
     * @param userId the value for SYS_USER_ORG.ACCOUNT_ID
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ORG.CREATE_TIME
     *
     * @return the value of SYS_USER_ORG.CREATE_TIME
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ORG.CREATE_TIME
     *
     * @param createTime the value for SYS_USER_ORG.CREATE_TIME
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ORG.CREATER
     *
     * @return the value of SYS_USER_ORG.CREATER
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ORG.CREATER
     *
     * @param creater the value for SYS_USER_ORG.CREATER
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ORG.UPDATE_TIME
     *
     * @return the value of SYS_USER_ORG.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ORG.UPDATE_TIME
     *
     * @param updateTime the value for SYS_USER_ORG.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ORG.UPDATER
     *
     * @return the value of SYS_USER_ORG.UPDATER
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ORG.UPDATER
     *
     * @param updater the value for SYS_USER_ORG.UPDATER
     *
     * @mbg.generated Mon Apr 16 09:22:07 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}