package com.easy.work.user.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.user.dto.UserDto;

import java.util.Date;

@Table(name = "sys_user")
public class UserDomain extends UserDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_ID
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    @Column(id = "USER_ID",length = 12,increment = true,rule = "US")
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_CODE
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private String userCode;

    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.STAFF_CODE
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private String staffCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_TEL
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private String userTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_NAME
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_TYPE
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_STATUS
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private String userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_WENXIN
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private String userWenxin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.USER_DING
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private String userDing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.CREATE_TIME
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.CREATER
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.UPDATE_TIME
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.UPDATER
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_ID
     *
     * @return the value of SYS_USER.USER_ID
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_ID
     *
     * @param userId the value for SYS_USER.USER_ID
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_CODE
     *
     * @return the value of SYS_USER.USER_CODE
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_CODE
     *
     * @param userCode the value for SYS_USER.USER_CODE
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.STAFF_CODE
     *
     * @return the value of SYS_USER.STAFF_CODE
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getStaffCode() {
        return staffCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.STAFF_CODE
     *
     * @param staffCode the value for SYS_USER.STAFF_CODE
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setStaffCode(String staffCode) {
        this.staffCode = staffCode == null ? null : staffCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_TEL
     *
     * @return the value of SYS_USER.USER_TEL
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_TEL
     *
     * @param userTel the value for SYS_USER.USER_TEL
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_NAME
     *
     * @return the value of SYS_USER.USER_NAME
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_NAME
     *
     * @param userName the value for SYS_USER.USER_NAME
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_TYPE
     *
     * @return the value of SYS_USER.USER_TYPE
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_TYPE
     *
     * @param userType the value for SYS_USER.USER_TYPE
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_STATUS
     *
     * @return the value of SYS_USER.USER_STATUS
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_STATUS
     *
     * @param userStatus the value for SYS_USER.USER_STATUS
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_WENXIN
     *
     * @return the value of SYS_USER.USER_WENXIN
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getUserWenxin() {
        return userWenxin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_WENXIN
     *
     * @param userWenxin the value for SYS_USER.USER_WENXIN
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setUserWenxin(String userWenxin) {
        this.userWenxin = userWenxin == null ? null : userWenxin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.USER_DING
     *
     * @return the value of SYS_USER.USER_DING
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getUserDing() {
        return userDing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.USER_DING
     *
     * @param userDing the value for SYS_USER.USER_DING
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setUserDing(String userDing) {
        this.userDing = userDing == null ? null : userDing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.CREATE_TIME
     *
     * @return the value of SYS_USER.CREATE_TIME
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.CREATE_TIME
     *
     * @param createTime the value for SYS_USER.CREATE_TIME
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.CREATER
     *
     * @return the value of SYS_USER.CREATER
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.CREATER
     *
     * @param creater the value for SYS_USER.CREATER
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.UPDATE_TIME
     *
     * @return the value of SYS_USER.UPDATE_TIME
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.UPDATE_TIME
     *
     * @param updateTime the value for SYS_USER.UPDATE_TIME
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.UPDATER
     *
     * @return the value of SYS_USER.UPDATER
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.UPDATER
     *
     * @param updater the value for SYS_USER.UPDATER
     *
     * @mbg.generated Sun Apr 15 16:53:11 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}