package com.easy.work.user.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Fields;
import com.easy.core.annotation.Table;
import com.easy.work.user.dto.UserArchivesDto;

import java.util.Date;

@Table(name = "sys_user_archives")
public class UserArchivesDomain extends UserArchivesDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.ARCHIVES_ID
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    @Column(id = "ARCHIVES_ID",rule = "AR",length = 12,increment = true)
    private String archivesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_ID
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_SEX
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_AGE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_PLACE_PROVINCE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String userPlaceProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_PLACE_CITY
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String userPlaceCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_ADDRESS
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String userAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_BIRTHDAY
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    @Fields(format = "yyyy-MM-dd")
    private Date userBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_HEADER_IMG
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String userHeaderImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_ENTRY_DATE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    @Fields(format = "yyyy-MM-dd")
    private Date userEntryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_QUIT_DATE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    @Fields(format = "yyyy-MM-dd")
    private Date userQuitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_CORR_DATE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    @Fields(format = "yyyy-MM-dd")
    private Date userCorrDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_POST
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String userPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_DEP
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String userDep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.USER_CID
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String userCid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.CREATER
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.CREATE_TIME
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    @Fields(format = "yyyy-MM-dd hh:mm:dd")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.UPDATER
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ARCHIVES.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    @Fields(format = "yyyy-MM-dd hh:mm:dd")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.ARCHIVES_ID
     *
     * @return the value of SYS_USER_ARCHIVES.ARCHIVES_ID
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getArchivesId() {
        return archivesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.ARCHIVES_ID
     *
     * @param archivesId the value for SYS_USER_ARCHIVES.ARCHIVES_ID
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setArchivesId(String archivesId) {
        this.archivesId = archivesId == null ? null : archivesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_ID
     *
     * @return the value of SYS_USER_ARCHIVES.USER_ID
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_ID
     *
     * @param userId the value for SYS_USER_ARCHIVES.USER_ID
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_SEX
     *
     * @return the value of SYS_USER_ARCHIVES.USER_SEX
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_SEX
     *
     * @param userSex the value for SYS_USER_ARCHIVES.USER_SEX
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_AGE
     *
     * @return the value of SYS_USER_ARCHIVES.USER_AGE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_AGE
     *
     * @param userAge the value for SYS_USER_ARCHIVES.USER_AGE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserAge(String userAge) {
        this.userAge = userAge == null ? null : userAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_PLACE_PROVINCE
     *
     * @return the value of SYS_USER_ARCHIVES.USER_PLACE_PROVINCE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUserPlaceProvince() {
        return userPlaceProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_PLACE_PROVINCE
     *
     * @param userPlaceProvince the value for SYS_USER_ARCHIVES.USER_PLACE_PROVINCE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserPlaceProvince(String userPlaceProvince) {
        this.userPlaceProvince = userPlaceProvince == null ? null : userPlaceProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_PLACE_CITY
     *
     * @return the value of SYS_USER_ARCHIVES.USER_PLACE_CITY
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUserPlaceCity() {
        return userPlaceCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_PLACE_CITY
     *
     * @param userPlaceCity the value for SYS_USER_ARCHIVES.USER_PLACE_CITY
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserPlaceCity(String userPlaceCity) {
        this.userPlaceCity = userPlaceCity == null ? null : userPlaceCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_ADDRESS
     *
     * @return the value of SYS_USER_ARCHIVES.USER_ADDRESS
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_ADDRESS
     *
     * @param userAddress the value for SYS_USER_ARCHIVES.USER_ADDRESS
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_BIRTHDAY
     *
     * @return the value of SYS_USER_ARCHIVES.USER_BIRTHDAY
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_BIRTHDAY
     *
     * @param userBirthday the value for SYS_USER_ARCHIVES.USER_BIRTHDAY
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_HEADER_IMG
     *
     * @return the value of SYS_USER_ARCHIVES.USER_HEADER_IMG
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUserHeaderImg() {
        return userHeaderImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_HEADER_IMG
     *
     * @param userHeaderImg the value for SYS_USER_ARCHIVES.USER_HEADER_IMG
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserHeaderImg(String userHeaderImg) {
        this.userHeaderImg = userHeaderImg == null ? null : userHeaderImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_ENTRY_DATE
     *
     * @return the value of SYS_USER_ARCHIVES.USER_ENTRY_DATE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public Date getUserEntryDate() {
        return userEntryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_ENTRY_DATE
     *
     * @param userEntryDate the value for SYS_USER_ARCHIVES.USER_ENTRY_DATE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserEntryDate(Date userEntryDate) {
        this.userEntryDate = userEntryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_QUIT_DATE
     *
     * @return the value of SYS_USER_ARCHIVES.USER_QUIT_DATE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public Date getUserQuitDate() {
        return userQuitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_QUIT_DATE
     *
     * @param userQuitDate the value for SYS_USER_ARCHIVES.USER_QUIT_DATE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserQuitDate(Date userQuitDate) {
        this.userQuitDate = userQuitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_CORR_DATE
     *
     * @return the value of SYS_USER_ARCHIVES.USER_CORR_DATE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public Date getUserCorrDate() {
        return userCorrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_CORR_DATE
     *
     * @param userCorrDate the value for SYS_USER_ARCHIVES.USER_CORR_DATE
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserCorrDate(Date userCorrDate) {
        this.userCorrDate = userCorrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_POST
     *
     * @return the value of SYS_USER_ARCHIVES.USER_POST
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUserPost() {
        return userPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_POST
     *
     * @param userPost the value for SYS_USER_ARCHIVES.USER_POST
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserPost(String userPost) {
        this.userPost = userPost == null ? null : userPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_DEP
     *
     * @return the value of SYS_USER_ARCHIVES.USER_DEP
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUserDep() {
        return userDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_DEP
     *
     * @param userDep the value for SYS_USER_ARCHIVES.USER_DEP
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserDep(String userDep) {
        this.userDep = userDep == null ? null : userDep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.USER_CID
     *
     * @return the value of SYS_USER_ARCHIVES.USER_CID
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUserCid() {
        return userCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.USER_CID
     *
     * @param userCid the value for SYS_USER_ARCHIVES.USER_CID
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUserCid(String userCid) {
        this.userCid = userCid == null ? null : userCid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.CREATER
     *
     * @return the value of SYS_USER_ARCHIVES.CREATER
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.CREATER
     *
     * @param creater the value for SYS_USER_ARCHIVES.CREATER
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.CREATE_TIME
     *
     * @return the value of SYS_USER_ARCHIVES.CREATE_TIME
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.CREATE_TIME
     *
     * @param createTime the value for SYS_USER_ARCHIVES.CREATE_TIME
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.UPDATER
     *
     * @return the value of SYS_USER_ARCHIVES.UPDATER
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.UPDATER
     *
     * @param updater the value for SYS_USER_ARCHIVES.UPDATER
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ARCHIVES.UPDATE_TIME
     *
     * @return the value of SYS_USER_ARCHIVES.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ARCHIVES.UPDATE_TIME
     *
     * @param updateTime the value for SYS_USER_ARCHIVES.UPDATE_TIME
     *
     * @mbg.generated Thu Jun 21 09:06:05 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}