package com.easy.work.user.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.easy.work.user.dto.UserAccountDto;

import java.util.Date;

@Table(name = "sys_user_account")
public class UserAccountDomain extends UserAccountDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    @Column(id = "ACCOUNT_ID",length = 12,rule = "AC",increment = true)
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ACCOUNT.USER_ID
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ACCOUNT.LOGIN_NAME
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ACCOUNT.PASSWORD
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ACCOUNT.STATUS
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ACCOUNT.ACCOUNT_LOCK
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    private String accountLock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ACCOUNT.CREATE_TIME
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ACCOUNT.CREATER
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ACCOUNT.UPDATE_TIME
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER_ACCOUNT.UPDATER
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ACCOUNT.ACCOUNT_ID
     *
     * @return the value of SYS_USER_ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ACCOUNT.ACCOUNT_ID
     *
     * @param accountId the value for SYS_USER_ACCOUNT.ACCOUNT_ID
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ACCOUNT.USER_ID
     *
     * @return the value of SYS_USER_ACCOUNT.USER_ID
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ACCOUNT.USER_ID
     *
     * @param userId the value for SYS_USER_ACCOUNT.USER_ID
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ACCOUNT.LOGIN_NAME
     *
     * @return the value of SYS_USER_ACCOUNT.LOGIN_NAME
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ACCOUNT.LOGIN_NAME
     *
     * @param loginName the value for SYS_USER_ACCOUNT.LOGIN_NAME
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ACCOUNT.PASSWORD
     *
     * @return the value of SYS_USER_ACCOUNT.PASSWORD
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ACCOUNT.PASSWORD
     *
     * @param password the value for SYS_USER_ACCOUNT.PASSWORD
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ACCOUNT.STATUS
     *
     * @return the value of SYS_USER_ACCOUNT.STATUS
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ACCOUNT.STATUS
     *
     * @param status the value for SYS_USER_ACCOUNT.STATUS
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ACCOUNT.ACCOUNT_LOCK
     *
     * @return the value of SYS_USER_ACCOUNT.ACCOUNT_LOCK
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public String getAccountLock() {
        return accountLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ACCOUNT.ACCOUNT_LOCK
     *
     * @param accountLock the value for SYS_USER_ACCOUNT.ACCOUNT_LOCK
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public void setAccountLock(String accountLock) {
        this.accountLock = accountLock == null ? null : accountLock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ACCOUNT.CREATE_TIME
     *
     * @return the value of SYS_USER_ACCOUNT.CREATE_TIME
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ACCOUNT.CREATE_TIME
     *
     * @param createTime the value for SYS_USER_ACCOUNT.CREATE_TIME
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ACCOUNT.CREATER
     *
     * @return the value of SYS_USER_ACCOUNT.CREATER
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ACCOUNT.CREATER
     *
     * @param creater the value for SYS_USER_ACCOUNT.CREATER
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ACCOUNT.UPDATE_TIME
     *
     * @return the value of SYS_USER_ACCOUNT.UPDATE_TIME
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ACCOUNT.UPDATE_TIME
     *
     * @param updateTime the value for SYS_USER_ACCOUNT.UPDATE_TIME
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER_ACCOUNT.UPDATER
     *
     * @return the value of SYS_USER_ACCOUNT.UPDATER
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER_ACCOUNT.UPDATER
     *
     * @param updater the value for SYS_USER_ACCOUNT.UPDATER
     *
     * @mbg.generated Mon Jun 25 12:03:32 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}